[book]
authors = ["yasutake"]
language = "ja"
multilingual = false
src = "src"
title = "Reiwa2"

[output.html]
theme = "src/theme"

[output.html.fold]
enable = true
level = 0

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
